version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
networks:
  mongodb_network:
    driver: bridge
volumes:
  mongodb_data:
    driver: local
